# server:
#   port: 8080

# spring:
#   application:
#     name: api-gateway

#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#       routes:
#         - id: mobile-banking
#           uri: lb://MOBILE-BANKING
#           predicates:
#             - Path=/mobile-banking/**
#         - id: mbankingpostgre
#           uri: lb://MBANKINGPOSTGRE
#           predicates:
#             - Path=/mbankingpostgre/**
#         - id: banking
#           uri: lb://BANKING
#           predicates:
#             - Path=/banking/**

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
